PDCMFinder/cancer-models

README.md

Added link to cancermodels.org text in readme file

[test-issue] Test issue more descriptive title goes here

---

.github/workflows/actions-test.yml
jest.config.js
jest.setup.js
package.json
src/components/Button/Button.stories.tsx
src/components/Button/Button.test.tsx
src/components/Button/Button.tsx
src/pages/index.tsx
yarn.lock

Fixes #15 
Installed Jest with configuration. Also added simple test for `button`
`yarn global add jest-cli`
`yarn test` or `yarn test:watch`

Install and setup Jest

---

.gitlab-ci.yml

Fix build-dev stage on GitLabCI

---

Dockerfile

Upgrade Docker dep to node:lts-buster

---

src/pages/about/providers.tsx
src/utils/providers.ts

Fixes #54 
Providers page always shows desktop navbar
Mobile simulation on http://localhost:3000/about/providers

Providers navbar

---

.gitlab-ci.yml

Fix CI/CD to remove wrong keys

---

public/static/content/about.md
public/static/content/privacy-policy.md
public/static/content/terms-of-use.md
src/components/Footer/Footer.tsx
src/components/Navbar/Navbar-desktop/Navbar-desktop.tsx
src/pages/about/index.tsx
src/pages/about/providers/[id].tsx
src/pages/about/providers/index.tsx
src/pages/privacy-policy.tsx
src/pages/terms-of-use.tsx
src/styles/globals.scss
src/utils/getProcessedContent.ts
src/utils/routes.ts

Resolves #63 
Create pages for content markdown files
`http://localhost:3000/about`
`http://localhost:3000/terms-of-use`
`http://localhost:3000/privacy-policy`

Markdown content pages

---

globalTypes.d.ts
src/apis/Search.api.ts
src/components/Input/Input.tsx
src/components/Input/InputAndLabel.tsx
src/components/SearchFilters/SearchFilterContent.tsx
src/components/SearchFilters/SearchFilters-mobile.tsx
src/pages/search.tsx
src/types/Facet.model.ts

Added User reducer for State management

50 ux sprint search page state use reducer

---

public/robots.txt
src/pages/sitemap.xml.ts
src/pages/sitemap1.xml.ts
src/pages/sitemap_index.xml.ts

closes #65 
Sitemap and robots for SEO
`http://localhost:3000/sitemap_index.xml`
`http://localhost:3000/sitemap.xml`
`http://localhost:3000/sitemap1.xml`
`http://localhost:3000/robots.txt`

Sitemap and robots

---

src/pages/data/models/[providerId]/[modelId].tsx

Remove extra useEffect check/loop

remove isInitialLoad from useEffect deps

---

src/components/Footer/Footer.tsx
src/components/Navbar/Navbar-mobile/Navbar-mobile.tsx

Fixes #78 
Update footer texts ,also from api
`localhost:3000` ; see footer

Update footer texts

---

src/apis/ModelDetails.api.ts
src/components/MolecularDataTable/MolecularDataTable.tsx

Fixes #77 
Adds links to Molecular data table
Clone, run and go to model details page and click on the view data button on the molecular data table

77 add external db links data to molecular data column

---

src/pages/index.tsx

Fixes #91 
Circle packing component not working correctly
yarn dev
go to localhost:3000
Click on the Digestive System Circle, see the search filtered
Go back to home and click on on of the smallest circles, see the search filtered

Fix Circle Packing component click behaviour

---

src/apis/ModelDetails.api.ts

99 empty column showing on data download

---

.gitlab-ci.yml

Change the PROD stages to run only on pushes to  main specifically

---

.gitlab-ci.yml
k8s-deploy/prod/deployment.yml
k8s-deploy/prod/service.yaml
src/pages/_app.tsx

Fixes hot jar build issue and CI CD configuration

Ci cd and hotjar fix

---

.env.production
k8s-deploy/prod/service.yaml

Fix production configuration domain

---

src/pages/_app.tsx

Fixes #126 
Add google analytics to track and receive data

Add google analytics script

---

src/components/FloatingWidget/FloatingWidget.module.scss
src/components/FloatingWidget/FloatingWidget.tsx
src/components/Layout/Layout.tsx

Fixes #128 
Floating widget for use on surverys
`localhost:3000` see button/widget on the right

Add floating widget with feedback survey

---

src/pages/overview.tsx

Fixes runtime issue with no data for plot

Removing the Donut Chart when there is no data

---

src/pages/_app.tsx

Remove hotjar tracking code from dev.cancermodels.org so we don't track unnecessarily

remove hotjar script from dev subdomain

---

src/components/MolecularDataTable/MolecularDataTable.tsx

Fixes
Add external sources db links to molecular data table
visit `http://localhost:3000/data/models/JAX/TM00097` > view Whole_Exome data

Add external db links

---

.env.production
k8s-deploy/prod/service.yaml
src/apis/ModelDetails.api.ts
src/components/FloatingWidget/FloatingWidget.module.scss
src/components/FloatingWidget/FloatingWidget.tsx
src/components/Layout/Layout.tsx

merge main branch

---

src/pages/data/models/[providerId]/[modelId].tsx
src/utils/getModelDetails.ts

Fixes #141 
Update raw data urls for molecular data
`http://localhost:3000/data/models/CMP/SIDM00872` see links in Raw Data column in Molecular Data table

Update molecular data raw data urls

---

src/pages/about/providers/[id].tsx
src/pages/about/providers/index.tsx

Fixes #140 
Replace spaces for hyphens in see all models link so when clicked, filters are correctly applied
visit http://localhost:3000/about/providers > scroll until Dana Farber > click "[See all DFCI CPDM models](http://localhost:3000/search?filters=data_source:DFCI-CPDM)" > search should filter accordingly

Replace spaces for hyphens in See All Models link

---

src/pages/index.tsx
src/pages/search.tsx

Fixes #84 
Move model count call to server so we don't have a flicker on model count
`localhost:3000` and see number of total models

Server side model count call

---

src/components/QualityBadge/QualityBadge.tsx
src/components/SearchResults/SearchResult/SearchResult.tsx
src/pages/data/models/[providerId]/[modelId].tsx

Fixes #170 
Easy readability 
`localhost:3000`

Always show quality badge text

---

src/components/SearchBar/SearchBar.tsx

Fixes #166 
Added label to search bar input so user has clear instructions on what to search
`http://localhost:3000/search` see on top of search bar

Add label to search bar input

---

src/apis/AggregatedData.api.ts
src/components/BarChart/BarChart.tsx
src/components/DonutChart/DonutChart.tsx
src/components/SunBurstChart/SunBurstChart.tsx
src/pages/index.tsx
src/pages/overview.tsx

Fixes #174 
Graphs on overview page are now clickable and send you toi the search page with filter applied
`localhost:3000/overview` click on any graph

Overview page clickable graphs

---

src/pages/overview.tsx

Fixes
Overview graph casing didn't work on filters

Fix overview casing

---

src/components/QualityBadge/QualityBadge.tsx

Fixes #178 
`http://localhost:3000/search`

change badge text

---

src/pages/about/index.mdx

About text update

---

src/pages/overview.tsx

subcategory bars

---

src/pages/_app.tsx
src/pages/data/models/[providerId]/[modelId].tsx

Spacing on big monitors on molecular data available ini model details apge
`http://localhost:3000/data/models/IRCC-CRC/CRC0161LM`

Molecular Data - Data available column spacing

---

src/apis/Search.api.ts
src/components/QualityBadge/QualityBadge.tsx
src/pages/search.tsx
src/utils/getModelDetails.ts

Fixes #204 
Change key values for scores; metadata and model characterisation
`localhost:3000` > see order of results and model characterisation/quality badge with updated scores

Update score keys

---

src/components/Button/Button.tsx
src/components/CookieConsent/CookieConsent.tsx
src/components/FloatingWidget/FloatingWidget.tsx
src/components/Layout/Layout.tsx
src/components/Modal/Modal.module.scss
src/components/Modal/Modal.tsx
src/components/Navbar/Navbar-desktop/Navbar-desktop.cy.js
src/components/Navbar/Navbar-mobile/Navbar-mobile.cy.js
src/components/Navbar/Navbar-mobile/Navbar-mobile.tsx
src/pages/data/models/[providerId]/[modelId].tsx
src/pages/search.tsx

Fixes #222 
Make feedback button/survey more visible so users can send feedback easily
`https://localhost:3000` > modal should open with feedback link

Feedback button more visible

---

src/pages/overview.tsx

Fixes #232 
Guide the users to /search seamlessly 
`https://localhost:3000/overview` > check first section

change wording and link style

---

package.json
src/pages/data/models/[providerId]/[modelId].tsx
yarn.lock

Fixes #239 
Optimize build times generating all pages on request on the server so we can still maintain good SEO. Pages are saved in cache for 10 minutes before having to request a new page. 
run `yarn build` > run `yarn start` > `https://localhost:3000/data/models/NKI/T250` still works as expected

Optimize build times

---

globalTypes.d.ts
src/components/Input/Label.tsx
src/pages/index.tsx
src/pages/overview.tsx
src/pages/search.tsx

Fixes #245 
Get total number of models from client so devs don't have to run build whenever data and not UI changes.
`http://localhost:3000/` and `http://localhost:3000/search` should have total number of models

Get total number of models from client

---

src/pages/submit.mdx

Fixes #258 
`http://localhost:3000/submit` links are seen there

Add metadata dictionary and validation links to submit page

---

src/components/DataCountCard/DataCountCard.module.scss
src/components/DataCountCard/DataCountCard.tsx
src/pages/index.module.scss
src/pages/index.tsx
src/pages/overview.module.scss
src/pages/overview.tsx
src/styles/_mixins.scss

Fixes #260 
Redesign home page for SEO and UX
`http://localhost:3000`
Mockup:

More concise home page

---

src/apis/ModelDetails.api.ts
src/apis/Search.api.ts
src/components/MolecularDataTable/MolecularDataTable.tsx
src/components/SearchFilters/SearchFilters.stories.tsx
src/components/SearchFilters/StoryMockData.ts
src/components/SearchResults/SearchResult/SearchResult.tsx
src/components/SearchResults/SearchResultsData-mock.js
src/mocks/data/dataset_available_facet.json
src/mocks/data/facet_sections.json
src/mocks/data/search_index.json
src/pages/compare.tsx
src/pages/data/models/[providerId]/[modelId].tsx
src/pages/submit.mdx

Fixes #268 
Update cytogenetics instances to biomarker
`http://localhost:3000/data/models/NKI/T283` > open biomarker data type row > notice how column title is "biomarker" and it shows all of them
`http://localhost:3000/search` > biomarker updated in Dataset Available filter and in result cards

update links and text

---

src/apis/Search.api.ts

Fixes #275 
Make UI make the correct call to the API for new filter
`http://localhost:3000/search` select a treatment type

Handle treatment type filter

---

public/static/providers/curie-bc.md
public/static/providers/curie-lc.md
public/static/providers/curie-oc.md

Curie provider name/title page was inconsistent
[Update data provider markdowns](https://github.com/PDCMFinder/cancer-models/issues/281)

provider name update

---

src/apis/ModelDetails.api.ts
src/pages/data/models/[providerId]/[modelId].tsx

Fixes #290 
Use new data restriction endpoint for better control
`http://localhost:3000/data/models/LIH/T356` > should show "No data" for `LIH0281T356PDOXNC1773RNABS2`
`http://localhost:3000/data/models/Curie-LC/LCF9` > table should show both request data and view data

New molecular data restriction endpoint

---

src/pages/data/models/[providerId]/[modelId].tsx

Fixes #294 
Change molecular data file extension to tsv from csv
`http://localhost:3000/data/models/NKI/T127` > click and Download Data button > see file extension

Change molecular data file extension to tsv

---

next.config.mjs
src/apis/ModelDetails.api.ts
src/pages/data/models/[providerId]/Model.module.scss
src/pages/data/models/[providerId]/[modelId].tsx
src/styles/_mixins.scss

Fixes #247 
Show model images from API
`http://localhost:3000/data/models/JAX/J000100674#histology-images`

Show model images

---

src/apis/ModelDetails.api.ts
src/middlewear.js
src/pages/data/models/[providerId]/Model.module.scss
src/pages/data/models/[providerId]/[modelId].tsx
src/styles/globals.scss

Fix 500 error on histology images

---

.vscode/launch.json
src/apis/ModelDetails.api.ts
src/apis/Search.api.ts
src/pages/data/models/[providerId]/[modelId].tsx
tsconfig.json

Fixes #311 
Add immune marker tables to model details page
`http://localhost:3000/data/models/JAX/TM01086#immune-markers`
`http://localhost:3000/data/models/CRL/CRL-1322#immune-markers`
`http://localhost:3000/data/models/CMP/SIDM00457#immune-markers`
`http://localhost:3000/data/models/PDMR/445649-340-R-V1-organoid`
`http://localhost:3000/data/models/PDMR/975524-054-R-V1-organoid`

Add immune marker tables to model details page

---

src/apis/AggregatedData.api.ts

Fixes #322 
Release note gitlab token expired - create and update token
http://localhost:3000/about/releases

Show UI release notes

---

src/pages/sitemap.xml.ts
src/pages/sitemap1.xml.ts
src/pages/sitemap_index.xml.ts

Fixes #332 
ADd https protocol to sitemaps so they can index better

Add https to sitemaps

---

src/pages/_app.tsx

Fixes #335 
Analytics scripts shouldn't be loading on dev environment

Conditional Script strategy

---

src/pages/contact.tsx
src/pages/data/models/[providerId]/[modelId].tsx

Fixes #339 
Add event triggers where user actions could be tracked for analytics data

Add analytics event triggers

---

src/components/Button/Button.module.scss
src/components/Button/Button.tsx
src/components/FeedbackIcon/FeedbackIcon.tsx
src/components/FloatingWidget/FloatingButton.tsx
src/components/Layout/Layout.tsx
src/styles/globals.scss

Fixes #341 
Adds a floating feedback bubble for small user surveys
`http://localhost:3000/` > see bottom right corner > click to open modal/survey

Floating feedback bubble

---

src/apis/ModelDetails.api.ts

Safety check model data

---

src/components/MolecularDataTable/MolecularDataTable.tsx
src/pages/about/index.mdx
src/pages/data/models/[providerId]/[modelId].tsx

Fixes #348 
Add Google Analytics events to strategic triggers

Google Analytics events

---

src/components/Footer/Footer.tsx
src/components/Navbar/Navbar-desktop/Navbar-desktop.tsx
src/utils/routes.ts

Fixes #349 
Event trigger for external API documentation link click

GA event trigger

---

src/utils/routes.ts

Fixes #353 
Update menu item to a more identifiable name
`localhost:3000` > hover "More" button on top nav / scroll and look at footer

Update CancerModels.Org (/about) route name

---

src/utils/routes.ts

Fixes #355 
Add cBioPortal instance to nav and footer items. No GA event needed
`localhost:3000` hover "More" nav button / look at footer

Add cBioPortal menu item

---

src/components/Footer/Footer.tsx
src/components/Navbar/Navbar-desktop/Navbar-desktop.tsx
src/components/Navbar/Navbar-mobile/Navbar-mobile.tsx
src/styles/globals.scss
src/utils/routes.ts

Fixes #357 
Adds Embl-ebi training nav item and fixes GA logic to support more items
`localhost:3000` see navigation menus / footer and nav

Add EMBL-EBI Training route to navs

---

src/pages/about/providers/index.tsx

Fixes #358 
Updates layout and adds cBioPortal instance link for the providers
`http://localhost:3000/about/providers` see and click "cBioPortal" buttons

Add cBioPortal link in providers

---

src/utils/routes.ts

Fixes #365 
Remove training nav item - moved to training page as a button

Remove EMBL-EBI training nav item

---

src/apis/ModelDetails.api.ts

Fixes #372 
fix `patientEthnicityAssessmentMethod`, `patientSampleSharable`, `patientSampleMonthsSinceCollection1`
`http://localhost:3000/data/models/Curie-BC/HBCx-31` download metadata, see all correct fields

Fix metadata typos

---

src/apis/ModelDetails.api.ts

Remove all instances of patientTreatmentStatus

---

src/components/ActiveLink/ActiveLink.tsx
src/components/Footer/Footer.tsx
src/components/Navbar/Navbar-desktop/Navbar-desktop.tsx
src/utils/routes.ts
types/globalTypes.d.ts

Fixes #378 
Allow any link to be opened in new tab

Add isBlank prop to links

---

src/components/ActiveLink/ActiveLink.tsx
src/components/Footer/Footer.tsx
src/components/Navbar/Navbar-desktop/Navbar-desktop.tsx
src/utils/routes.ts
types/globalTypes.d.ts

Fixes #382 
Update isBlank prop name to a more descriptive name

Update isBlank prop name

---

src/components/Footer/Footer.tsx
src/pages/about/index.mdx

Remove 01 at the end of footer numbers

---

src/pages/_app.tsx

Fixes #399 
Add https:// to canonical page urls

Fix canonicals

---

src/pages/compare.tsx

Fixes #408 
Didn't render well without `_app.tsx` initial props

Fix compare page router

---

src/apis/ModelDetails.api.ts
src/apis/Search.api.ts
src/components/MolecularDataTable/MolecularDataTable.tsx
src/pages/compare.tsx
src/pages/data/models/[providerId]/[modelId].tsx
src/types/ModelData.model.ts
src/utils/parseRelationships.ts

Model detail page updated for invitro specific data

---

src/pages/data/models/[providerId]/[modelId].tsx

Send ploidy to end of immune marker table

---

src/apis/ModelDetails.api.ts
src/apis/Search.api.ts

Fixes #416 
For in vitro models, show corresponding metadata score
/search

Update in vitro models metadata score

---

src/pages/data/models/[providerId]/[modelId].tsx
src/utils/constructMolecularDataFilename.ts

Fixes #412 
Add ID to files/state so there wont be duplicate checks and single file downloads

Molecular data batch download multiple file download fix

---

src/apis/Search.api.ts
src/components/SearchFilters/SearchFilterContent.tsx
src/components/SearchFilters/StoryMockData.ts
src/pages/search.tsx
src/types/Facet.model.ts

Fixes #420 
Add check filter options based on boolean conditions 
`http://localhost:3000/search` > tick Paediatric filter

Adds logic for boolean filters

---

src/pages/data/models/[providerId]/[modelId].tsx

Fixes #427 
Serialize extLinks

Serialize extLinks on model page

---

src/apis/ModelDetails.api.ts
src/pages/data/models/[providerId]/[modelId].tsx
src/types/ModelData.model.ts

Fixes #424 
`http://localhost:3000/data/models/TRACE/EMC0047PR`

Metadata download file includes all engraftment and qc rows

---

src/apis/Search.api.ts
src/pages/search.tsx
src/types/Facet.model.ts

Fixes #422 
Use filter operators received from api instead of handling logic on FE

Use api operators on filters

---

src/components/FloatingWidget/FloatingButton.tsx
src/components/Layout/Layout.tsx
src/pages/compare.tsx
src/pages/data/models/[providerId]/[modelId].tsx
src/pages/search.tsx
src/types/ModelData.model.ts

Fixes #413 
We need more users to answer this form, adding text might attract them to click and answer (and know what to expect when clicking)

Add text to floating feedback bubble

---

src/components/Banner/Banner.tsx
src/components/EMBLBanner/EMBLBanner.tsx
src/components/Layout/Layout.tsx

Fixes #430 
Add temporal banner
`localhost:3000`

Add EMBL-EBI Services survey banner

---

src/pages/data/models/[providerId]/[modelId].tsx

Fixes #436 
Relationships > related models

Update model relationship table titles

---

src/pages/data/models/[providerId]/[modelId].tsx

Fixes #438 
Add file to all mol data downloads

Add quality control file to molecular data downloads

---

src/apis/Search.api.ts

Fix Search by cancer diagnosis not working

---

src/apis/Search.api.ts
src/components/Footer/Footer.tsx
src/pages/compare.tsx
src/pages/search.tsx
src/utils/routes.ts
src/utils/tourSteps.ts

Fixes #448  #447  #446 
Take out Contact from "more"
Add validator and dictionary to "more"

Nav elements updates

---

public/static/providers/idi-irccs.md
public/static/providers/irccs-ior.md
src/pages/about/providers/[id].tsx
src/pages/about/providers/index.tsx

#462 Markdown files for new providers

462 provider pages

---

src/components/Layout/Layout.tsx
src/pages/submit/submission-process.mdx

Fixes #466 
Remove EMBL temporary survey banner
`https://localhost:3000`

Remove EMBL banner

---

src/pages/search.tsx

Add facet operator query data as search result deps

---

src/pages/submit/submission-process.mdx

Fixes #476 
sprocess > submission process
`/submit/submission-process`

Fix submission process typo

---

src/components/SearchResults/SearchResult/SearchResult.tsx
src/pages/about/providers/index.tsx
src/pages/compare.tsx

Fixes #478 
Add width to quality badge

Fix quality badge width

---

src/apis/Search.api.ts
src/components/SearchResults/SearchResult/SearchResult.tsx

Hotfix: replace broken 'ù' character

---

src/pages/index.tsx

Fix provider image name casing

---

src/apis/ModelDetails.api.ts
src/components/ExternalModelLinksTable/ExternalModelLinksTable.tsx
src/pages/data/models/[providerId]/[modelId].tsx
src/types/ModelData.model.ts

Fixes #487 
Add identifiers and supplier IDs to model pages
http://localhost:3000/data/models/BROD/HCM-BROD-0106-C71

add external ids table

---

src/components/ExternalModelLinksTable/ExternalModelLinksTable.tsx
src/pages/data/models/[providerId]/[modelId].tsx
src/styles/globals.scss

Responsive table title and download buttons

---

src/apis/Search.api.ts
src/components/SearchResults/SearchResults.tsx
src/pages/search.tsx

Fixes #494 
Only first digit was being used, sorry

Use all digits for page selection

---

src/components/SearchResults/SearchResult/SearchResults.stories.tsx
src/components/SearchResults/StoryMockData.ts

Fixes #515 
Add mock data and modelAvailable argument

Add model availability data to search results story

---

src/apis/AggregatedData.api.ts
src/apis/ModelDetails.api.ts
src/components/HierarchyTree/CustomNode.module.scss
src/components/HierarchyTree/CustomNode.tsx
src/components/HierarchyTree/HierarchyTree.tsx
src/pages/data/models/[providerId]/[modelId].tsx
src/styles/globals.scss
src/types/ModelData.model.ts
src/utils/dataUtils.ts
src/utils/hooks/useActiveProject.ts
src/utils/parseKnowledgeGraph.ts
src/utils/parseRelationships.ts
tsconfig.json
types/globalTypes.d.ts

Fixes #517 
Use knowledge graph data

Update model relationship graphs

---

src/components/ModelPurchaseButton/ModelPurchaseButton.tsx

Fixes #519 
Update from "Purchase model at [supplier]"  to "Purchase [id]"
`http://localhost:3000/data/models/CMP/SIDM01753`

Update purchase model button text

---

src/apis/ModelDetails.api.ts
src/pages/data/models/[providerId]/[modelId].tsx
src/styles/_types.scss
src/types/ModelData.model.ts

Fixes #525 
Add date of submission
Open any model, see top of banner

Add model date of submission

---

src/apis/ModelDetails.api.ts
src/pages/data/models/[providerId]/[modelId].tsx
src/styles/globals.scss
src/types/ModelData.model.ts
src/utils/dataUtils.ts

Add external links to patient treatment table

---

src/apis/Search.api.ts
src/components/SearchResults/SearchResult/SearchResult.tsx
src/pages/data/models/[providerId]/[modelId].tsx

Fixes #530 
Update filter section names and sort filters by index value

Update filter sections and sorting value

---

src/apis/ModelDetails.api.ts

Fixes #534 
Remove model type check to allow organoids to show their data
`http://localhost:3000/data/models/HKU/GX048-TO`

Show drug dosing data for non-pdx models

---

src/apis/ModelDetails.api.ts
src/pages/data/models/[providerId]/[modelId].tsx
src/types/ModelData.model.ts

Show external resource links for model treatments

---

src/pages/tutorials.tsx

Fixes #538 
Add A guide to identifying suitable patient-derived cancer models in CancerModels.Org to tutorials page with CC BY credits
`http://localhost:3000/tutorials`

Add webinar to tutorials page

---

src/components/Icons/CloseIcon/CloseIcon.tsx
src/components/Navbar/Navbar-mobile/Navbar-mobile.module.scss
src/components/Navbar/Navbar-mobile/Navbar-mobile.tsx
src/pages/_app.tsx
src/utils/handleBodyClass.tsx

Fixes #540 
Menu was overflowing and couldn't be scrolled in some mobile devices
inspect, resize

Fit mobile menu to shorter devices

---

src/components/SearchBar/SearchBar.tsx
src/components/SearchFilters/MultivaluedSearchFilter.tsx

Fixes #545 
Typeahead data wouldn't update so options wouldn't update

Fix search and filter inputs options bug

---

src/components/Card/Card.tsx
src/components/SearchFilters/MultivaluedSearchFilter.tsx
src/pages/tutorials.tsx

Fixes #544 
Use youtube so tutorials page is consistent and code is cleaner

use type all around

---

src/components/SearchBar/SearchBar.tsx
src/components/SearchFilters/MultivaluedSearchFilter.tsx
src/components/SearchFilters/SearchFilterContent.tsx
src/pages/search.tsx

Fixes #551 
Filters aren't using url values

Fix default values from url state on filters

---

src/utils/parseRelease.ts

Fixes #553 
Parse tables
http://localhost:3000/about/releases

Support tables on release notes

---

src/components/SearchBar/SearchBar.tsx
src/pages/index.tsx
src/utils/hooks/useActiveProject.ts
src/utils/projects.ts

Fixes #555 
Rotate 'em
Refresh it

Dynamic home page selected project

---

src/hooks/useActiveProject.ts
src/pages/about/providers/index.tsx
src/pages/index.tsx
src/utils/projects.ts

Fixes #557 
Randomize providers
`http://localhost:3000/?project=HCMI` > refresh and refresh

Providers from project tabs are dynamic

---

src/hooks/useActiveProject.ts
src/pages/index.tsx

Static providers in home page

---

src/pages/data/models/[providerId]/[modelId].tsx

Model page link conditional rendering

---

public/static/providers/irccs-ire.md
src/components/Input/InputAndLabel.tsx
src/components/Input/Select.tsx
src/components/SearchBar/SearchBar.tsx
src/components/SearchFilters/MultivaluedSearchFilter.tsx
src/components/SearchFilters/SearchFilterContent.tsx
src/pages/data/models/[providerId]/[modelId].tsx
src/pages/search.tsx

Fixes #572 
Allow inputs to show test in Hotjar recordings, to better debug
NA

Allow Hotjar to record non-sensitive text inputs

---

src/components/Icons/ModelTypeIcon.tsx
src/pages/data/models/[providerId]/[modelId].tsx

Fixes #576 
Better layout for all different diagnosis text lengths
`http://localhost:3000/data/models/CMP/SIDM01025`
`http://localhost:3000/data/models/CUIMC/SCBO-8_Organoid_P11`
etc

Fix model type icon layout on model pages

---

src/apis/ModelDetails.api.ts
src/pages/data/models/[providerId]/[modelId].tsx
src/types/ModelData.model.ts

Add passage to treatment tables

---

src/apis/Search.api.ts
src/utils/projectSettings.json

Fixes #584 
Change Other tab to say More
visit home

Change Other to More in projects

---

src/apis/AggregatedData.api.ts

Fixes #587 
Update Gitlab tokens for release log
http://localhost:3000/about/releases

Update Gitlab api release tokens

---

src/components/Modal/Modal.module.scss
src/components/Navbar/Navbar.tsx
src/styles/globals.scss

Fixes #590 
Having a fix for the under construction modal broke the width on other modals. Made a class to just use on under construction modal
view some model data and should work just fine

Fix modal sizing over medium breakpoint

---

src/components/Icons/ModelTypeIcon.tsx
src/pages/data/models/[providerId]/[modelId].tsx
src/pages/search.tsx
src/types/css.d.ts
src/utils/tourSteps.ts

Fixes #592 
Update driver steps and dynamic import

Update Driver.js tours

---

src/components/HierarchyTree/HierarchyTree.tsx
src/pages/data/models/[providerId]/[modelId].tsx

Fixes #598 
Click on "Biomarkers" on a search result

Search results available data hyperlink scrolls to table

---

src/pages/data/models/[providerId]/[modelId].tsx

Fixes #596 
Add tooltip on hover

Add tooltip to model type icon on model page

---

src/components/Icons/MouseIcon.tsx
src/components/Input/InputAndLabel.tsx
src/components/SearchResults/SearchResult/SearchResult.module.scss
src/components/SearchResults/SearchResult/SearchResult.tsx
src/components/Tooltip/Tooltip.tsx
src/styles/_mixins.scss
src/styles/globals.scss

Fixes #600 
Outline and move position
`https://localhost:3000/search`

Make add to compare button more prominent

---

public/static/providers/irccs-cro.md

Fixes #602 
Had to update providers name to match API name
`http://localhost:3000/about/providers/irccs-cro`

Update IRCCS-CRO name

---

src/pages/privacy-policy.mdx

Update Privacy Policy text

---

src/pages/compare.tsx
src/pages/search.tsx

Fixes #610 
Let the user know, without alerts, that there's a minimum and a maximum amount of models to be able to compare
Add less than 1 model to compare and add more than 4 models. In the compare page, try to leave only 1 model

Better compare flow ux

---

src/pages/data/models/[providerId]/[modelId].tsx
src/utils/constructMolecularDataFilename.ts

Fixes #621 
Fixes a bug where molecular data file wasn't being added to .zip contents
Click "DOWNLOAD DATA" on a molecular data row

Update hit limit of models to compare alert (#609)
