PDCMFinder/cancer-models

- README.md
Fixes https://github.com/PDCMFinder/cancer-models/issues/5
In the readme file, cancermodels.org doesn't open in external page
Click link for cancermodels.org in readme file
> [readme-link] added https:// to link

- src/pages/about/index.mdx
- src/utils/routes.ts
Fixes #79 
Update menu items; 
About PDCM Finder > PDCM Finder
Hide Metadata Dictionary and FAQ
`localhost:3000` see menu
`http://localhost:3000/about`  we're keeping page title and url as About
> Update menu items

- src/components/Navbar/Navbar-desktop/Navbar-desktop.module.scss
Fixes #92 
Go to search page, apply a filter, try clicking on nav item "search"; page wont refresh nor change url state
> Disable clicking on same nav item that user is currently in

- src/pages/search.tsx
Fixes #106 
Enable the user to sort by metadata score
`localhost:3000/search` > click "sort by:" select, click any Metadata option
> Score sort options

- src/pages/search.tsx
Fixes #104 
After updating a filter, user would be scrolled all the way to the top, causing an annoyance. Removed this scroll to top from this action
`yarn dev` > `localhost:3000/search` > select a filter a notice you stay in same scroll position
> Don't scroll to top after filter is selected

- src/components/CookieConsent/CookieConsent.module.scss
- src/styles/globals.scss
fix layering in model id sidebar and cookie consent
Visit `http://localhost:3000/data/models/PMLB/PHLC422` in desktop, sidebar "menu" should be under cookie consent
> fix z-index on sidebar and cookie consent

- src/components/SearchFilters/SearchFilterContent.tsx
Fixes #111 
"typing" backspace added an empty value, removed "pop-value" action from onChange
`http://localhost:3000/search` > click on a typeahead and hit backspace ; nothing should happen
> Hitting backspace on empty typeahead adds a blank character selection

- src/components/QualityBadge/QualityBadge.tsx
Fixes #145 
Let the user know what the meter is for
`localhost:3000/search` and hover over the quality meter in the results card
`http://localhost:3000/data/models/UOC-BC/AB551M1` and hover over the quality meter in the header
> Quality badge tooltip

- src/components/SearchResults/SearchResult/SearchResult.module.scss
- src/components/SearchResults/SearchResult/SearchResult.tsx
- src/styles/globals.scss
Fixes 
Better layout for available data in search result card
`localhost:3000/search` see result cards
> Minor - Adjust layout for available data in search result cards

- src/pages/search.tsx
Format total results number so it appears with a coma when it needs to
`localhost:3000/search` > see total results in "Showing ..." text
> Minor - Format total results number

- next.config.mjs
- src/pages/_app.tsx
Remove experimental feature from config, add display: swap. This stops the website from loading with a different font
`localhost:3000`
> Remove font experimental feature

- src/components/SearchResults/SearchResult/SearchResult.tsx
- src/pages/data/models/[providerId]/[modelId].tsx
Fixes #153 
Hide badge if score is 0 so it doesn't look empty
`localhost:3000/search` > sort by metadata ascending 
onal)
> Hide quality badge if score is 0

- src/components/SearchFilters/SearchFilterContent.tsx
Fixes #168 
In the FE, change multiple selection labels so the user can distinguish easier what they do
Open molecular data accordion
> On multiple selections, change "all" and "any" labels

- public/static/providers/luriechildrens.md
Fixes #158 
Img url on md wasn't camel case
`https://www.cancermodels.org/about/providers` > see Ann & Robert H Lurie Children's Hospital of Chicago section
> Fix Ann & Robert image url

- src/apis/Search.api.ts
Fixes #193 
`localhost:3000/search` > in patient ethnicity filter pick an option that includes ";" > models should be shown in results
> Support filtering options with ";"

- .env.production
- .env.staging
- src/pages/_app.tsx
Fixes #195 
Load analytic (hotjar, google) scripts only on production. This to have the same file in prod, dev and staging for easier merging
`localhost:3000` > network tab shouldn't load any hotjar or google scripts
> Analytics scripts only on production

- src/components/SearchFilters/SearchFilterContent.tsx
Fixes #197 
Do nothing if clicking backspace on a searchable multivalue filter
`http://localhost:3000/search` > click on multivalue filter eg.Datasource and hit backspace > nothing happens
> Multivalue filter - No option is added when hitting backspace

- src/apis/Search.api.ts
- src/components/BarChart/BarChart.tsx
- src/components/SearchFilters/SearchFilterContent.tsx
- src/pages/overview.tsx
- src/pages/search.tsx
- src/utils/collapseEthnicity.ts
Fixes #179 
Ethnicity filter and overview chart have same top level categories. When filtering by them, results show subcategories
`localhost:3000/search` > open patient ethnicity filter > notice only top level categories > click to see results of subcategories
`localhost:3000/overview` > observe ethnicity count chart > notice only top level categories > click to see results of subcategories
> Group ethnicity filter categories

- src/pages/search.tsx
Fixes #208 
When clicking on [enabled] filter clear button, cancer diagnosis search terms (top bar) don't clear
`http://localhost:3000/search?filters=model_type%3Aorganoid+AND+search_terms%3AEsophageal+Adenocarcinoma` > click filter clear button > see cancer diagnosis term still there
> Search page - filter button only clears filters

- src/pages/compare.tsx
Fixes #209 
• Same height header cards - push qbadge to baseline
• link header model id to model page
`http://localhost:3000/compare?models=BB6RC160+AB551M1+T250` > see qbadge all at the same height / link model id from header
> Compare page fixes

- src/pages/search.tsx
Fixes #212 
Page goes to 1 when user changes the search results order
`http://localhost:3000/search?filters=page%3A5` > change sorting order > should be back on page 1
> Search page - Reset page on sort change

- src/components/QualityBadge/QualityBadge.tsx
Fixes #219 
Show a tooltip with the quality badge score when hovering
`http://localhost:3000/search` > hover over any quality badge
`http://localhost:3000/data/models/UOM-BC/BB6RC37` > hover over quality badge
> Show score on quality badge hover

- src/components/QualityBadge/QualityBadge.module.scss
- src/components/QualityBadge/QualityBadge.tsx
Fixes #223 
Add descriptive text for users to understand what the score/badge means
`http://localhost:3000/search` > hover quality badge
> Quality badge - Include descriptive text

- src/pages/contact.tsx
Fixes #234 
Show status messages so the user can have better knowledge of what happened when submitting form
In contact.tsx, change response value to `{ error: "" }` for success submission and `{ error: "foo" }` for error submission > send contact form
> Contact form status messages

- src/components/Input/Input.tsx
Input onChange had conditions that didn't allow it from triggering when needed
> Fix input onChange

- src/pages/data/models/[providerId]/[modelId].tsx
Fixes #241 
Sidebar links replace current URL for better user navigation
`http://localhost:3000/data/models/NKI/T250` > click on a couple of sidebar links > go back on your browser > should take you to previous page
> Model details page sidebar links replace current URL

- src/pages/compare.tsx
Fixes #249 
Hide sections where there would be no data- they're not relevant
`http://localhost:3000/compare?models=SIDM01288+SIDM01291+SIDM01279` > no engraftment and qdata sections since they're organoids
`http://localhost:3000/compare?models=SIDM01288+T394` > still show section since at least 1 model has data
> Compare - hide empty sections

- src/pages/data/models/[providerId]/[modelId].tsx
Fixes #251 
Show external resource on raw data column in molecular data table
`http://localhost:3000/data/models/IRCC-CRC/CRC0131LM` > Should show resources
`http://localhost:3000/data/models/CRL/CRL-1114` > shouldn't show resources ("Not available")
> Show external resource on raw data column in molecular data table

- src/components/Tooltip/Tooltip.module.scss
- src/components/Tooltip/Tooltip.tsx
Fixes #253 
Now able to copy tooltip text; higher than other elements
`http://localhost:3000/compare?models=T241+T127+T283+CRL-508`
> Tool tip - z-index, copyable

- src/components/ActiveLink/ActiveLink.tsx
- src/components/Button/Button.tsx
- src/components/Footer/Footer.tsx
- src/pages/sitemap.xml.ts
- src/utils/routes.ts
Fixes #262 
Update page names so they're more concise, add some pages that we're in `/about` to the nav submenu
`http://localhost:3000` > see nav menu and footer > hover `About` button on nav
> Update page names, add pages to submenu

- src/components/Layout/Layout.tsx
- src/components/Modal/Modal.tsx
- src/pages/data/models/[providerId]/[modelId].tsx
- src/styles/globals.scss
Fixes #295 
Remove empty/unused scrollbars from tables and from feedback modal on Windows + Firefox 
Windows + firefox > `http://localhost:3000/data/models/NKI/T250`
> Remove extra scroll bars in model details page tables

- src/pages/about/index.mdx
Fixes #299 
Add organizations link to about page so users can use/edit/view our open source code
`http://localhost:3000/about` > scroll and view link
> Add repositories link to about page

- src/apis/Search.api.ts
Fixes #305 
Add endpoint to multivalued facet list so it uses `ov.` operator
`http://localhost:3000/search?filters=immunemarkers_names%3AHLA-A%2CHLA-B%2CHLA-C` should show results
`http://localhost:3000/search` > use immunemarkers filter
> Add support to immunemarker data

- src/pages/search.tsx
Fixes #307 
Move pagination position so it's underneath the search results when filters are open, instead of always at the bottom of the page
`http://localhost:3000/search` > open filters > notice pagination is always just under search results
> Move pagination position

- src/components/SearchResults/SearchResult/SearchResult.tsx
Fixes #314 
Add space to `bio markers` in search result card
`http://localhost:3000/search?filters=dataset_available%3Abio+markers`
> Bio markers spelling in search result card

- src/pages/compare.tsx
Fixes #324 
Adds immune marker row to available data in comapre page as a checkmark if any is vavailable, empty column if not
`http://localhost:3000/compare?models=T336+T250+CRL-1876+CRL-1584` > see there's checkmarks and empty columns
> Add immune marker row to available data in compare page

- src/components/Modal/Modal.module.scss
Fixes #350 
Mobile search filters in modal now have a min-height of "initial", so they can work on Safari
`localhost:3000/search` on mobile > open filter modal and scroll down
> Set min height for modal / mobile search filters

- src/components/Footer/Footer.tsx
Fixes #388 
Adds EBI data preservation link to the end of the footer
Scroll all the way to the bottom of the footer, see new line
> Add EBI data preservation link

- .vscode/settings.json
- src/apis/ModelDetails.api.ts
- src/components/ImageChecker/ImageChecker.tsx
- src/pages/data/models/[providerId]/[modelId].tsx
- src/types/ModelData.model.ts
- src/utils/imageIsBrokenChecker.ts
Fixes #457 
We shouldn't show broken images, it's bad ui
`http://localhost:3000/data/models/JAX/TM00025#histology-images`
`http://localhost:3000/data/models/CRL/CRL-401#histology-images`
> Don't show broken histology images

- src/pages/data/models/[providerId]/[modelId].tsx
Fixes #459 
External images aren't loading for histology images when using next/image
At the time of this issue: `https://dev.cancermodels.org/data/models/JAX/TM00025#histology-images`
`http://localhost:3000/data/models/JAX/TM00025#histology-images`
> Change Image component to img tag for histology images

- src/pages/search.tsx
Fixes #468 
Search results are loading before fetching operators, making calls to api with fallback/default (maybe wrong) operators
use filters
> Fetch facet operators before search results (useQuery.enable)

- src/pages/data/models/[providerId]/[modelId].tsx
- src/pages/search.tsx
Fixes #472 
Show card when the user clicks "download all" on molecular data
`http://localhost:3000/data/models/PDMR/269647-328-T` > Click download all
> Show file tracker card when downloading all molecular data

- src/pages/about/providers/index.tsx
- src/pages/index.tsx
- src/utils/hooks/useActiveProject.ts
- src/utils/projects.ts
- src/utils/sortArrBy.ts
Fixes #502 
Add full provider names for easy identification since there are some repeated logos. Also good for SEO
`localhost:3000`
> Home page: Add provider names to provider logos 

- src/pages/compare.tsx
- src/pages/index.tsx
Fixes #504 
Add model type icons to compare page models
`http://localhost:3000/compare?models=SIDM01378+HCM-CSHL-0246-C19+CRL-508+HCM-BROD-0106-C71`
> Add model type to compare page

- src/components/ModelPurchaseButton/ModelPurchaseButton.tsx
Fixes #507 
Append linkLabel to resourceLabel only for ATCC supplier
http://localhost:3000/data/models/BROD/HCM-BROD-0198-C71
> Add label to ATCC supplier puchase button

- src/components/Accordion/Accordion.stories.tsx
- src/components/Accordion/Accordion.tsx
- src/components/SearchFilters/MultivaluedSearchFilter.tsx
- src/components/SearchFilters/SearchFilterContent.tsx
- src/components/SearchFilters/SearchFilters.tsx
- src/utils/dataUtils.ts
Fixes #523 
Clear filter options when onBlur so they aren't maintained from Select to Select
Type 'e' on Treatment Type filter, then type 'e' on Model Drug Dosing filter. There should be different options
> Clear filter options when blur

- src/pages/search.tsx
- src/utils/typeaheadStyles.ts
Fixes #581 
Give the user a better "no results" message, showing the filters they've selected
`http://localhost:3000/search?filters=model_type%3Acell+line+AND+data_source%3ACDH+AND+has_relations%3Atrue+AND+project_name%3AHCMI`
> Show a better "no results" message

- src/components/SearchResults/SearchResult/SearchResult.tsx
- src/pages/about/providers/[id].tsx
- src/pages/data/models/[providerId]/[modelId].tsx
Fixes #626 
update getStaticProps to use the id in lowercase to get data
> Provider page accepts upper or lowercase IDs in URL
